### ISSUE TITLE
Questions about the object queries

### ISSUE THREAD

**Issue by JuewenPeng** [xdxie/WAS_WordArt-Segmentation#3]
Really nice work!

I have some questions about the N object queries in Fig. 4. How many queries do you set in your implementation, and do you gather all queries for only one binary mask output, which differs from Mask2Former?

**Comment by xdxie** [comment]
Thank you for your interest. We set 50 queries for the text objects. Like most text segmentation models, we only focus on text objects. For the inference and post-processing, we actually follow the setting as Mask2Former without special design. The final output is one binary mask.
